kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: petclinic-build-workspace
  namespace: demo-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
  volumeMode: Filesystem