apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: spring-petclinic
  namespace: demo-cicd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
